SET SQL DIALECT 3;
CREATE TABLE TEST_TABLE (
    ID      BIGINT GENERATED BY DEFAULT AS IDENTITY,
    XVALUE  VARCHAR(50)
);

ALTER TABLE TEST_TABLE ADD CONSTRAINT PK_TEST_TABLE PRIMARY KEY (ID);



SET TERM ^ ;

create or alter procedure TEST_PROCEDURE
returns (
    X varchar(25))
as
begin
  /* Procedure Text */
  X = 'hello world';
  suspend;
end^

SET TERM ; ^

/* Existing privileges on this procedure */

GRANT EXECUTE ON PROCEDURE TEST_PROCEDURE TO SYSDBA;